name: Update submodules

on:
  workflow_dispatch: ~
  repository_dispatch:
    types:
      - site-update

permissions:
  contents: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - name: Update remote submodules
        run: git submodule update --init --remote
      - name: Commit submodule updates
        run: |
          git commit -am "Automatic submodule update"
          git push
